waganeko_proj/waganeko/urls.py
from django.urls import path
from waganeko.views import hello, mypage, book, author, mypage
# ルーティングの設定

app_name = 'waganeko'
urlpatterns = [
    path('hello/', hello.hello, name='hello'),
    path('mypage', mypage.mypage_top, name='mypage_top'),#追加！
    path('book/<slug:book_id>', book.detail_view, name='book_detail'),
    path('book/<slug:book_id>/<slug:explanation_id>', book.detail_view2, name='book_detail2'),
    path('book/', book.list_view, name='book_list'),
    path('book/search/', book.list_search_view, name='book_search_list'),
    path('author/', author.list_view, name='author_list'),
    path('author/<slug:author_id>', author.detail_view, name='author_detail'),
    path('newpost/<slug:book_id>', book.new_explanation_post, name='new_explanation_post'),
    # path('posts/', book.explanation_posts, name='explanation_posts'),
    path('form/<slug:book_id>', book.form_view, name='post_form'),
    path('delete/<slug:explanation_post_id>/<slug:book_id>', book.delete, name='delete'),
    path('like/<slug:explanation_post_id>/<slug:book_id>', book.like, name='like'),
    path('dislike/<slug:explanation_post_id>/<slug:book_id>', book.dislike, name='dislike'),
    # path('update/<slug:explanation_post_id>/', book.update, name='update'),
]

waganeko_proj/waganeko_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from waganeko.views.register import register_view, done_view
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from waganeko.models import Book
# from .index import index

def index(request):
    book_list = Book.objects.all().order_by('view_nums').reverse()[:6]
    return render(request,'index.html', {'book_list':book_list})

def test(request):
    return render(request, 'test.html')

urlpatterns = [
    path('test/', test, name='test'),
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('waganeko/', include('waganeko.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register_view, name='register'),
    path('accounts/register/done', done_view, name='register_done'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waganeko_proj/waganeko/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
GENDER_LIST = ( (0, '男性'), (1, '女性') )
dict_gender_list = {0:'男性',1:'女性'}
book_category_list = ((0, '小説'), (1, '科学'))
dict_book_category_list = {0:'小説', 1:'科学'}


# class Followed(models.Model):
#     class Meta:
#         verbose_name = 'フォロワー名'
#         verbose_name_plural = 'フォロワー名'

#     id = models.CharField(max_length=6,primary_key=True)

class Profile(models.Model):
    class Meta:#Djangoの使用、インナークラスといい、Profileがどういう情報かを設定する
        verbose_name = 'ユーザー情報データ'
        verbose_name_plural = 'ユーザー情報データ'

    user = models.OneToOneField(User, verbose_name='ユーザー',null=True, blank=True, on_delete=models.CASCADE)
    email = models.EmailField('email', blank=False, unique=True)
    id = models.CharField(max_length=6,primary_key=True)
    #U00001から
    username = models.CharField('ユーザー名', max_length=30)
    age = models.IntegerField('年齢')
    gender = models.IntegerField('性別',choices=GENDER_LIST)
    prefer_book_category = models.IntegerField('好きな本のカテゴリ', choices=book_category_list, null=True)
    icon_img = models.ImageField(upload_to='image/', null=True)
    belong = models.CharField('所属', max_length=30, null=True)
    # follower = models.ManyToManyField(Followed, blank=True)


    def __str__(self):
        user_str = ''
        if self.user is not None:
            user_str = '(' + self.user.username + ')'
        #加筆ここまで

        return self.id+' '+str(self.age)+'歳 ' \
            +dict_gender_list.get(self.gender)+' ' \
            +user_str

#------------------------------------------------------------------------------------------------------


class Author(models.Model):
    class Meta:
        verbose_name = '著者データ'
        verbose_name_plural = '著者データ'

    id = models.CharField(max_length=6, primary_key=True)
    #A00001から
    last_name = models.CharField('著者苗字', max_length=30, null=True)
    first_name = models.CharField('著者名', max_length=30, null=True)
    last_name_hiragana = models.CharField('著者苗字ひらがな', max_length=30, null=True)
    first_name_hiragana = models.CharField('著者名ひらがな', max_length=30, null=True)
    born_year = models.CharField('生まれた年', max_length=20, null=True)
    pass_away_year = models.CharField('享年', max_length=20, null=True)
    detail = models.TextField('著者について詳細', null=True)
    author_img = models.ImageField(upload_to='image/', null=True)

    def __str__(self):
        if self.first_name:
            return self.id + ' ' + self.last_name + ' ' + self.first_name
        else:
            return self.id + ' ' + self.last_name
        # return self.id + ' ' + self.last_name + ' ' + self.first_name

class Publisher(models.Model):
    class Meta:
        verbose_name = '出版社'
        verbose_name_plural = '出版社'
    id = models.CharField(max_length=6, primary_key=True)
    #P00001から
    name = models.CharField('出版社名', max_length=30)
    other = models.TextField('詳細', null=True)


class Book(models.Model):
    class Meta:
        verbose_name = '本データ'
        verbose_name_plural = '本データ'

    id = models.CharField(max_length=6, primary_key=True)
    #I00001から
    book_name = models.CharField('本の名前', max_length=50)
    book_name_hiragana = models.CharField('本の名前（読み仮名）', max_length=50, null=True)
    author = models.ForeignKey(Author, verbose_name='著者',null=True, on_delete=models.CASCADE)
    # publisher = models.ForeignKey(Publisher, verbose_name='出版社', on_delete=models.CASCADE, null=True)
    first_published_year = models.CharField('出版年', max_length=5, null=True)
    text = models.TextField('本文', null=True)
    category = models.IntegerField('本のカテゴリ', choices=book_category_list, null=True)
    rate = models.IntegerField('評価', default=0, null=True)
    page_nums = models.IntegerField('ページ数', null=True)
    book_img = models.ImageField(upload_to='image/', null=True)
    view_nums = models.PositiveIntegerField('閲覧数', default=0)

    def __str__(self):
        return self.id + ' ' + self.book_name + ' 著者ID:' + self.author.id

class Summary(models.Model):
    class Meta:
        verbose_name = 'あらすじ'
        verbose_name_plural = 'あらすじ'

    id = models.CharField(max_length=6, primary_key=True)
    #S00001から
    post_user = models.ForeignKey(Profile, verbose_name='投稿者', on_delete=models.CASCADE)
    post_text = models.TextField('投稿', max_length=100)
    iine_nums = models.PositiveIntegerField('いいね数')
    category = models.PositiveIntegerField('カテゴリ', choices=book_category_list, null=True)
    posted_time = models.DateTimeField(auto_now_add=True)
    post_for_book = models.ForeignKey(Book, verbose_name='投稿先の本', on_delete=models.CASCADE)

class Explanation(models.Model):
    class Meta:
        verbose_name = '解説'
        verbose_name_plural = '解説'

    id = models.CharField(max_length=6, primary_key=True)
    #E00001から
    post_user = models.ForeignKey(Profile, verbose_name='投稿者', on_delete=models.CASCADE, null=True)
    # post_text = models.CharField('投稿内容', max_length=150)
    tweet = models.TextField('ツイート', default="")
    iine_nums = models.PositiveIntegerField('いいね数', default=0)
    igiari_nums = models.PositiveIntegerField('異議あり数', default=0)
    category = models.PositiveIntegerField('カテゴリ', choices=book_category_list, null=True)
    posted_time = models.DateTimeField(auto_now_add=True, null=True)
    total_nums = models.PositiveIntegerField('合計数', default=0)
    post_for_book = models.ForeignKey(Book, verbose_name='投稿先の本', related_name="explanation",  on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.post_user.id + ' ' + self.tweet + self.id

class Like(models.Model):
    class Meta:
        verbose_name = 'なるほど～'
        verbose_name_plural = 'なるほど～'

    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='like_user')
    explanation = models.ForeignKey(Explanation, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

class Dislike(models.Model):
    class Meta:
        verbose_name = '異議あり'
        verbose_name_plural = '異議あり'

    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='dislike_user')
    explanation = models.ForeignKey(Explanation, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

class ScoreLog(models.Model):
    class Meta:
        verbose_name = '本評価データ'
        verbose_name = '本評価データ'

    profile = models.ForeignKey(Profile, verbose_name='ユーザー情報', on_delete=models.CASCADE)
    score = models.IntegerField('評価')                         # 1~5
    timestamp = models.DateTimeField('日時', auto_now_add=True)

waganeko_proj/waganeko/views/author.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib.auth.decorators import login_required #追加！
from django.contrib import messages


from django.core.paginator import Paginator
from waganeko.models import Author, ScoreLog

import random

message_rate_created = '評価が登録されました！'
message_rate_updated = '評価が更新されました！'

def list_view(request):

    if request.method == 'POST':
        if 'author_id_list' in request.POST:
            author_list = Author.objects.all().order_by('-id')
        elif 'author_views_list' in request.POST:
            author_list = Author.objects.all().order_by('view_nums').reverse()
    else:
        author_list = Author.objects.all().order_by('-id')
    paginator = Paginator(author_list, 20) # ページ当たり20個表示

    try:
        page = int(request.GET.get('page'))
    except:
        page = 1

    authors = paginator.get_page(page)
    return render(request, 'waganeko/author_list.html', {'authors': authors, 'page': page, 'last_page': paginator.num_pages})

#追加！
def detail_view(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    # author.view_nums += 1
    # author.save()
    try:
        page = int(request.GET.get('from_page'))
    except:
        page = 1

    # try:
    #     log = ScoreLog.objects.get(profile_id=request.user.profile.id, booook_id=book_id)
    #     current_score = log.score
    # except:
    #     current_score = -1

    # return render(request, 'waganeko/book_detail.html', {'book': book, 'page': page, 'current_score':current_score })
    return render(request, 'waganeko/author_detail.html', {'author': author, 'page': page})


# #追加！
# @login_required
# def rate(request, rentroom_id):
#     rentroom = get_object_or_404(RentRoom, id=rentroom_id)

#     log, created = ScoreLog.objects.update_or_create( \
#         defaults = {'score':request.POST.get('score')},
#         profile_id = request.user.profile.id,
#         rent_room_id = rentroom_id,
#     )

#     if created:
#         messages.success(request, message_rate_created)
#     else:
#         messages.success(request, message_rate_updated)

#     return redirect('iekari:rentroom_detail', rentroom_id=rentroom_id)

waganeko_proj/waganeko/views/hello.py
from django.http import HttpResponse
from django.shortcuts import render

def hello(request):
    return HttpResponse('hello')    

waganeko_proj/waganeko/views/mypage.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from waganeko.models import Book, Explanation
import json
from django.db.models import Prefetch
# from waganeko.models import


@login_required
def mypage_top(request):
    user = request.user
    profile = user.profile

    explanation_list = list(Explanation.objects.select_related('post_for_book').filter(iine_nums__gt=0))

    book_id_list = []
    for explanation in explanation_list:
        book_id = explanation.post_for_book.id
        book_id_list.append(book_id)

    books = []
    for book_id in book_id_list:
        book = Book.objects.get(id=book_id)
        books.append(book)
    books = set(books)
    books = list(books)

    return render(request, 'waganeko/mypage.html', {'profile':profile, 'books':books}) #'assessments':myassessments

waganeko_proj/waganeko/views/register.py
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from waganeko.register_form import RegisterForm

class RegisterView(CreateView):
    template_name = 'registration/register_form.html'
    form_class = RegisterForm
    success_url = reverse_lazy('register_done')

register_view = RegisterView.as_view()

class DoneView(TemplateView):
    template_name = 'registration/register_done.html'

done_view = DoneView.as_view()

waganeko_proj/waganeko/templates/waganeko/author_detail.html
{% extends "subbase.html" %}
{% load mathfilters %}
{% load static %}

{% block title %}著者の詳細{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">著者の詳細</h4>

<table class="table table-striped table-bordered">
    <tbody>
        <tr>
            <th scope="row">著者ID</th>
            <td>{{ author.id }}</td>
        </tr>
        <tr>
            <th scope="row">著者の名前</th>
            <td>{{ author.last_name }} {{ author.first_name | default:"" }}</td>
        </tr>
        <tr>
            <th scope="row">読み仮名</th>
            <td>{{ author.last_name_hiragana }}{{ author.first_name_hiragana }}</td>
        </tr>
        <tr>
            <th scope="row">生年月日</th>
            <td>{{ author.born_year }}</td>
        </tr>
        <tr>
            <th scope="row">没年</th>
            <td>{{ author.pass_away_year }}</td>
        </tr>
        <tr>
            <th scope="row">詳細</th>
            <td>{{ author.detail | default:"" }}</td>
        </tr>
    </tbody>
</table>


<a href="{% url 'waganeko:author_list' %}?page={{ page }}">一覧へ戻る</a>
{% endblock %}





{% block extra_js %}
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-tilelayer-geojson/1.0.4/TileLayer.GeoJSON.min.js"></script>
<script src="{% static 'iekari/js/map_preview.js' %}"></script>
{% endblock %}

waganeko_proj/waganeko/templates/waganeko/author_list.html
{% extends "subbase.html" %}
{% load mathfilters %}

{% block title %}著者の一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">著者の一覧</h4>

<!-- <div class="btn-group btn-group-toggle" data-toggle="buttons">
  <form action="{% url 'waganeko:author_list' %}" method="post" name="book_id_list">
  <label class="btn btn-primary active">
    <input type="radio" name="author_id_list" id="option1" autocomplete="off" checked>物件ID順
  </label>
  </form>
  <form action="{% url 'waganeko:author_list' %}" method="post" name="book_views_list">
  <label class="btn btn-primary">
    <input type="radio" name="author_views_list" id="option2" autocomplete="off">閲覧数順
  </label>
  </form>
</div> -->

<table class="table table-striped table-bordered table-dark">
    <thead>
        <tr>
            <th scope="col">著者ID</th>
            <th scope="col">著者名</th>
            <th scope="col">著者名読み仮名</th>
            <th scope="col">生年月日</th>
            <th scope="col">没年</th>
            <!-- <th scope="col">詳細</th> -->

        </tr>
    </thead>
    <tbody>
        {% for author in authors %}
        <tr>
            <th scope="row"><!---変更--->
                <a href="{% url 'waganeko:author_detail' author_id=author.id %}">
                    {{ author.id }}
                </a>
            </th>
            <td>{{ author.last_name }} {{ author.first_name | default:"" }}</td>
            <td>{{ author.last_name_hiragana }}{{ author.first_name_hiragana | default:"" }}</td>
            <td>{{ author.born_year }}</td>
            <td>{{ author.pass_away_year }}</td>
            <!-- <td>{{ author.detail | default:""}}</td> -->

        </tr>
        {% endfor %}
    </tbody>
</table>

{% if page > 1 %}
<a href="{% url 'waganeko:author_list' %}?page={{ page|sub:1 }}">前のページ</a>
{% endif %}
{% if page < last_page %}
<a href="{% url 'waganeko:author_list' %}?page={{ page|add:1 }}">次のページ</a>
{% endif %}
{% endblock %}

waganeko_proj/waganeko/templates/waganeko/book_detail.html
{% extends "subbase.html" %}
{% load mathfilters %}
{% load static %}

{% block title %}本の詳細{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">本の詳細:{{ book.book_name }}</h4>


<table class="table table-striped table-bordered">
    <tbody>
        <tr>
            <th scope="row">本ID</th>
            <td>{{ book.id }}</td>
        </tr>
        <tr>
            <th scope="row">本の名前</th>
            <td>{{ book.book_name }}</td>
        </tr>
        <tr>
            <th scope="row">読み仮名</th>
            <td>{{ book.book_name_hiragana }}</td>
        </tr>
        <tr>
            <th scope="row">著者</th>
            <td>{{ book.author }}</td>
        </tr>
        <tr>
            <th scope="row">初版本出版年</th>
            <td>{{ book.first_published_year | default:"" }}</td>
        </tr>
        <tr>
            <th scope="row">category</th>
            <td>{{ book.category | default:""}}</td>
        </tr>
        <tr>
            <th scope="row">評価</th>
            <td>{{ book.rate |default:""}}</td>
        </tr>
        <tr>
            <th scope="row">ページ数</th>
            <td>{{ book.page_nums |default:""}}</td>
        </tr>
        <tr>
            <th scope="row">閲覧数</th>
            <td>{{ book.view_nums }}</td>
        </tr>

    </tbody>
</table>
{% if book.book_img %}
<img src="{{ book.book_img.url }}" class="img-fluid">
{% endif %}
{% if book.text %}
<details class="bg-light border-bottom">
    <summary>
        <h4>本文</h4>
    </summary>
    {{ book.text }}
</details>
{% endif %}
<div class="container bg-light">
    <h3>解説</h3>
    {% if explanations %}
    {% for i in explanations %}
    <div class="container border border-dark rounded">
        <ul class="list-unstyled">
            <li>{% if i.post_user.icon_img %}
                <img src="{{ i.post_user.icon_img.url }}" class="img-fluid" width="100" height="100">
                {% endif %}
                UserName：{{i.post_user.user.username}}</li>
            <li> 所属：{{i.post_user.belong | default:"" }}</li>
            <li>
            </li>
        </ul>
        解説：{{i.tweet}} <br><a class="btn btn-danger"
            href="{% url 'waganeko:delete' explanation_post_id=i.id book_id=book.id%}">削除</a>
        <a class="btn btn-success"
            href="{% url 'waganeko:like' explanation_post_id=i.id book_id=book.id %}">なるほど～:{{ i.iine_nums }}</a>
        <a class="btn btn-warning"
            href="{% url 'waganeko:dislike' explanation_post_id=i.id book_id=book.id %}">異議あり:{{ i.igiari_nums }}</a>
    </div>
    {% endfor %}
    {% else %}
    <h5>解説がありません。</h5>
    {% endif %}
    <form action="{% url 'waganeko:post_form' book_id=book.id %}" method="POST" name="new_post">
        {% csrf_token %}
        <input type=submit class="btn btn-dark" value=投稿する>
    </form>
</div>
<a href="{% url 'waganeko:book_list' %}?page={{ page }}" class="btn btn-light">一覧へ戻る</a>
{% endblock %}





{% block extra_js %}
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-tilelayer-geojson/1.0.4/TileLayer.GeoJSON.min.js"></script>
<script src="{% static 'iekari/js/map_preview.js' %}"></script>
{% endblock %}

waganeko_proj/waganeko/templates/waganeko/book_list.html
{% extends "subbase.html" %}
{% load mathfilters %}

{% block title %}本の一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">本の一覧</h4>
<h3>{{ message }}</h3>


<form action="{% url 'waganeko:book_list' %}" method="post">
        {% csrf_token %}
        <!-- <div class="btn-group btn-primary  row"> -->
            <input type="submit" class="btn btn-primary" name="sort" value="閲覧数順">
    <input type="submit" class="btn btn-primary" name="sort" value="ID順">
</form>
<form action="{% url 'waganeko:book_search_list' %}"  method="get">
  <input type="text" class="" name="search" placeholder="検索ワードを入力">
  <input type="submit" class="btn btn-success" value="検索">
  </form>

<table class="table table-striped table-bordered table-dark">
    <thead>
        <tr>
            <th scope="col">pic</th>
            <th scope="col">本ID</th>
            <th scope="col">本の名前</th>
            <th scope="col">著者</th>
            <th scope="col">初版出版年</th>
            <th scope="col">カテゴリ</th>
            <th scope="col">ページ数</th>
            <th scope="col">評価</th>
            <th scope="col">閲覧数</th>

        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
          <th scope="row"><!---変更--->
            {% if book.book_img %}
            <img src="{{ book.book_img.url }}" class="img-fluid" width="100" height="100">
            {% endif %}
          </th>
            <td>
                <a href="{% url 'waganeko:book_detail' book_id=book.id %}">
                    {{ book.id }}
                </a>
            </td>
            <td>{{ book.book_name}}</td>
            <td>{{ book.author.last_name }}{{ book.author.first_name }}</td>
            <td>{{ book.first_published_year | default:"" }}</td>
            <td>{{ book.category | default:"" }}</td>
            <td>{{ book.page_nums | default:"" }}</td>
            <td>{{ book.rate | default:""}}</td>
            <td>{{ book.view_nums }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if page > 1 %}
<a href="{% url 'waganeko:book_list' %}?page={{ page|sub:1 }}">前のページ</a>
{% endif %}
{% if page < last_page %}
<a href="{% url 'waganeko:book_list' %}?page={{ page|add:1 }}">次のページ</a>
{% endif %}
{% endblock %}

waganeko_proj/waganeko/templates/waganeko/explanation.html
{% extends "subbase.html" %}
{% load mathfilters %}
{% load bootstrap4 %}

{% block title %}投稿{% endblock title %}

    {% block content %}
    <h1>解説</h1>
        {% for i, f in explanations %}
           <ul>
               <li>
                   {{f}} <a href="{% url 'waganeko:delete' explanation_post_id=i %}">削除</a>
               </li>
           </ul>
        {% endfor %}
        <a href="{% url 'waganeko:post_form' %}" class="btn btn-dark">解説を投稿する</a>
    {% endblock content %}

waganeko_proj/waganeko/templates/waganeko/explanation_new_post.html
{% extends "subbase.html" %}
{% load mathfilters %}
{% load bootstrap4 %}

{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% block title %}Expplanation{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">解説を投稿</h4>
    <p>本のID：{{ book_id }}</p>
<form action="{% url 'waganeko:new_explanation_post' book_id=book_id %}" method="POST" name="new_post">
      {% csrf_token %}
{% bootstrap_form form layout='horizontal' %}
    <!-- <input type="textarea" name="new_post" maxlength="140"> -->
        <button type="submit" value="投稿" class="btn btn-dark">投稿する</button>

</form>
{% endblock content %}

waganeko_proj/waganeko/templates/waganeko/mypage.html
{% extends "subbase.html" %}
{% load mathfilters %}

{% block title %}マイページ{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">マイページ</h4>

    <h5>基本情報</h5>
    <p><b>{{ user.username }}</b> さん</p>
    <p>年齢: {{ user.profile.age }}歳</p>
    <p>性別: {{ user.profile.get_gender_display }}</p>
    <p>所属: {{ user.profile.belong }}</p>
    {% if user.profile.icon_img %}
    <img src="{{ user.profile.icon_img.url }}" class="img-fluid" width="100" height="100">
    {% endif %}
<h5>あなたが「なるほど～」をした本の一覧</h5>
    <table class="table table-striped table-bordered table-dark">
        <thead>
            <tr>
                <th scope="col">Pic</th>
                <th scope="col">本ID</th>
                <th scope="col">本の名前</th>
                <th scope="col">著者</th>
                <th scope="col">閲覧数</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <th scope="row"><!---変更--->
                  {% if book.book_img %}
                  <img src="{{ book.book_img.url }}" class="img-fluid" width="100" height="100">
                  {% endif %}
                </th>
                <td>
                    <a href="{% url 'waganeko:book_detail' book_id=book.id %}">
                        {{ book.id }}
                    </a>
                </td>
                <td>{{ book.book_name}}</td>
                <td>{{ book.author.last_name }}{{ book.author.first_name }}</td>
                <td>{{ book.view_nums }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>



    <p>ユーザー名またはパスワードの編集は <a href="/accounts">こちら</a>(未実装)</p>
<!--
    <hr>
    <h5>物件評価履歴</h5>

    <table class="table table-striped table-bordered">
    <thead>
        <tr>
        <th scope="col">物件ID</th>
        <th scope="col">詳細</th>
        <th scope="col">評価</th>
        </tr>
    </thead>
    <tbody>
        {% for log in logs %}
        <tr>
        <th scope="row">
            {{ log.rent_room.id }}
        </th>
        <td>
                {{ log.rent_room.id }}
            </a>
        </td>
        <td>{{ log.score }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

    <hr>
    <h5>所有物件</h5>

    <table class="table table-striped table-bordered">
    <thead>
        <tr>
        <th scope="col">物件ID</th>
        <th scope="col">詳細</th>
        <th scope="col">価格</th>
        </tr>
    </thead>
    <tbody>
        {% for room in rooms %}
        <tr>
        <th scope="row">
            {{ room.id }}
        </th>
        <td>
                {{ room }}
            </a>
        </td>
        <td>{{ room.price }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

    <hr>
    <h5>追加待ちの所有物件</h5>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
            <th scope="col">物件ID</th>
            <th scope="col">詳細</th>
            <th scope="col">査定価格</th>
            </tr>
        </thead>
        <tbody>
            {% for assess in assessments %}
            <tr>
            <th scope="row">
                {{ assess.id }}
            </th>
            <td>
                    {{ assess }}
                </a>
            </td>
            <td>
                {{ assess.price }}
            </td>
            </tr>
            {% endfor %}
        </tbody>
    </table> -->
{% endblock %}

waganeko_proj/waganeko/templates/waganeko/update.html
{% extends "subbase.html" %}
{% load mathfilters %}
{% load bootstrap4 %}

{% block title %}投稿{% endblock title %}

    {% block content %}
    <h1>ツイート編集</h1>
<form action="{% url 'waganeko:update' %}" method="post" name="update_post">
{% csrf_token %}
  <table>
    {{ new_explanation }}
    <tr><td colspan='2'><input type="submit" value="Submit"></td></tr>
  </table>
    {% endblock content %}